### ISSUE TITLE
List of daily tasks

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-project#1]
## Value Proposition

**As a** User
**I need** a list of daily tasks
**to be able to** read them.

## Description

<img width="200" alt="UserStory01" src="https://user-images.githubusercontent.com/102236373/179204191-355b0feb-d3b2-48c4-86aa-61ef8b592c29.png">

## Acceptance Criteria

- [x] A heading at the top of the page for orientation in which category of tasks you are currently in.
- [x] A short description of the following tasks between headline and list.
- [x] A short description of the daily tasks are displayed in a list.

## Tasks

(for developers team)

- [x] Global Styles
- [x] Storybook
- [x] Create component/DailyTasks
- [x] Create component/TaskList
- [x] Write tests
- [x] Add to App
