### ISSUE TITLE
Check off finished tasks

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-project#2]
## Value Proposition

**As a** User
**I need** checkboxes for each task
**to be able to** check it off as done.

## Description

<img width="200" alt="UserStory02" src="https://user-images.githubusercontent.com/102236373/179225705-918a5031-e811-42df-bd42-923dfc5d417a.png">

## Acceptance Criteria

- [x] Each task needs its own checkbox
- [x] The checkboxes are unchecked by default
- [x] Once the user has completed a task he can check it off

## Tasks

(for developers team)

- [x] Create feature branch 
- [x] Add checkbox to daily task component
