### ISSUE TITLE
Save completed tasks

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-project#3]
## Value Proposition

**As a** User
**I want** to save my completed tasks
**to be able to** access the edited list even if I have closed the app.

## Description

<img alt="UserStory03" src="https://user-images.githubusercontent.com/102236373/179237038-3ff64d7c-ca00-4617-a86e-c9c7c3f81938.png">

## Acceptance Criteria

- [x] The status of the checkboxes should be saved for one day.
- [x] At the start of a new day, the tasks should be displayed again as unfinished/unchecked.

## Tasks

(for developers team)

- [x] Add a value for the unfinished/completed tasks to the database.
- [x] OR:  Add a value for the unfinished/completed tasks to local storage.
- [x] Make sure that the tasks are reset daily.
- [x] Add to Storybook
- [x] Write Test
