### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-project#4]
## Value Proposition

**As a** User
**I need**  a Homepage
**to be able to** see my current tasks.

## Description

<img width="226" alt="UserStory_04" src="https://user-images.githubusercontent.com/102236373/179480051-e9efb0f0-d2c4-4ff7-a2a9-7ad46f1d5757.png">

## Acceptance Criteria

- [x] I have a home page that displays the card component "täglich".
- [x] The page title „Aktuelle Aufgaben“ is displayed above the "täglich" component.

## Tasks

(for developers team)

- [x] create HomePage.js
- [x] add "täglich" tasks as a card component to the homepage
- [x] Add to Storybook
- [x] Write tests
