### ISSUE TITLE
(Data for db) List of tasks for the current day

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-project#5]
## Value Proposition

**As a** Developer
**I need** data (a list with tasks and an image)
**to be able to** fill the database.

## Description

**Montags**
*Heute setzen wir den Fokus auf das Bad.*
- Dusche reinigen inkl. Fliesen, 
  Armaturen und Sieb
- Badewanne reinigen inkl. 
  Abflusssieb
- Zahnputzbecher reinigen
- Spiegel putzen
- Alle Oberflächen, Griffe und
  Schalter reinigen
- Toilette gründlich innen & außen
- Mülleimer leeren
- Boden saugen
- Boden nass wischen
- Handtücher tauschen

**Dienstags**
*Heute sagen wir dem Staub den Kampf an.
Schnapp dir den Staubsauger und los!*
- Spinnweben an den Decken
- Alle Böden
- Unter den Betten
- Fußleisten
- Polstermöbel 
- Bilderrahmen und Dekoration
- Staubsauger reinigen und 
  verräumen

**Mittwochs**
*Mit Putzeimer und Lappen ausgestattet
wischen wir heute feucht über die Oberflächen.*
- Fensterbänke
- Regale, Tische, Kommoden &
  sonstige Oberflächen
- Zimmerpflanzen
- Türgriffe/Lichtschalter/Klingel/
  Lampen
- Geländer/Handlauf im Treppen-
  haus
- Bilderrahmen und Dekoration
- Fernseher/Laptop/Handy
- Flächen auf hohen Schränken
  und Regalen

**Donnerstags**
*Fast geschafft! Heute sorgen wir für einen
glasklaren Blick und duftende Bettwäsche.*
- Bettwäsche wechseln und 
  waschen
- Alle Böden feucht wischen
- Fenster/Glasflächen bei Bedarf
- Bügeln
- Bettwäsche ggf. bügeln, 
  zusammenlegen und verräumen

**Freitags**
*Hunger? Mit Fokus auf die Küche erstellen wir
heute den Menüplan für nächste Woche.*
- Küchenfronten reinigen
- Kühlschrank ausräumen
- Kühlschrank auswischen
- Vorräte kontrollieren
- Einkaufszettel aktualisieren
- Wochenplan für Mahlzeiten 
- Altglas wegbringen
- Altpapier wegbringen
- Pfandgut zurückgeben
- Einkauf einräumen

**Samstags & sonntags**
*Lehn dich zurück und genieß dein Wochenende!*
<img width="300" alt="funny-dog" src="https://user-images.githubusercontent.com/102236373/179741329-9c298b4a-891e-45f4-914f-18f3c02b6b96.png">

## Acceptance Criteria

- [x] A list with **headlines**, *descriptions* and tasks for each weekday (Mo-Fr).
- [x] A **headline**, *description* and an image for the weekend (Sa+So).

## Tasks

(for developers team)

- [x] Fill db with template data.
- [x] Save the image in the folder images/weekend
