### ISSUE TITLE
(user) List of tasks for the current day

### ISSUE THREAD

**Issue by alicie232** [alicie232/capstone-project#6]
## Value Proposition

**As a** User
**I need** a list of tasks
**to be able to** check each task off as done.

## Description
<img alt="UserStory_05" src="https://user-images.githubusercontent.com/102236373/179548727-a344b321-13e3-4719-afc5-1da6a5621ffd.png">

<img alt="UserStory_05-weekend" src="https://user-images.githubusercontent.com/102236373/179742041-1a023ffb-6de7-48e4-800c-bb95fcd07866.png">

## Acceptance Criteria

- [x] A second card with the *weekly tasks*, displayed under the first card of *daily tasks*.
- [x] Only the daily (täglich) and the weekly (e.g. Montags) recurring tasks for the current day are displayed.
- [x] The structure of the second card is the same as the first card (title, description, checkable list of tasks).
- [ ] On weekends (samstags & sonntags ), instead of the tasks, a funny picture is displayed as a reward for the completed tasks.
- [x] The homepage is scrollable.

## Tasks

(for developers team)

- [x] Add the weekly tasks for the current day to homepage.
- [x] Add weekend card to Storybook.
- [x] Add demo picture *funny dog* for the weekend card.
- [ ] Write tests.
